/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class task_bipolarchat_nativej_HTest */

#ifndef _Included_task_bipolarchat_nativej_HTest
#define _Included_task_bipolarchat_nativej_HTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     task_bipolarchat_nativej_HTest
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_task_bipolarchat_nativej_HTest_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
